apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx  
spec:
 containers: 
 - name: animals
   volumeMounts:
  - name: app-storage
    mountPath: /storage
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
 - name: spring-music
   volumeMounts:
   - name: app-storage
     mountPath: /storage
   image: yanivomc/spring-music:latest 
   ports: 
   - containerPort: 8080

volumes:
 - name: app-storage
   hostPath:
    path: /tmp/files
